/**
 * Generated Claude Code `PreToolUse` pre-edit hook (v0.21.17, ADR-067).
 *
 * ADR-067 establishes that Claude Code's `PreToolUse` hook is the *one* platform
 * seam where a real pre-edit veto on an agent's proposed edit is possible. The
 * extension does not intercept anything itself — it *generates* this opt-in hook,
 * which pipes the proposed file content to `rac validate - --corpus <dir>` and
 * blocks the Edit/Write only when `rac` reports a structural finding (a reference
 * to a retired or missing decision, or a malformed artifact). All validation
 * lives in `rac` (ADR-063); the hook computes nothing.
 *
 * The hook config format and the script body are generated from this single
 * module so the format lives in one place — the roadmap's churn mitigation.
 * Everything here is honest about scope: this is Claude-Code-specific. Other
 * clients rely on the v0.21.16 post-edit guard.
 */

/** Relative path (from the workspace root) of the generated hook script. */
export const HOOK_SCRIPT_RELPATH = ".claude/hooks/rac-preedit.py";

/** Relative path of the Claude Code project settings the hook registers in. */
export const CLAUDE_SETTINGS_RELPATH = ".claude/settings.json";

/** A stable marker so a generated registration can be found and replaced. */
export const HOOK_COMMAND_MARKER = "rac-preedit.py";

/** The tool matcher: Write/Edit/MultiEdit are the file-mutating tools. */
export const HOOK_MATCHER = "Write|Edit|MultiEdit";

/**
 * The body of the generated hook script.
 *
 * Written in Python because `rac` already requires Python, so the interpreter is
 * present wherever the hook can do anything useful, and Python gives robust JSON
 * parsing and subprocess control — far safer than shell string-munging of the
 * PreToolUse payload.
 *
 * Contract (Claude Code `PreToolUse`):
 *  - reads the event JSON on stdin: `tool_name`, `tool_input` (with `file_path`
 *    and, for Write, `content`; for Edit/MultiEdit, the edits);
 *  - acts only on Markdown files under the corpus directory — every other file
 *    is an immediate allow (exit 0);
 *  - reconstructs the *proposed* full content (Write carries it directly; Edit /
 *    MultiEdit are applied to the on-disk file in memory) and pipes it to
 *    `rac validate - --corpus <corpus>`;
 *  - blocks the edit with exit code 2 and the finding on stderr **only** when
 *    `rac` exits non-zero (a structural finding); otherwise exits 0;
 *  - FAILS OPEN: any internal error (missing `rac`, unreadable file, unexpected
 *    payload) exits 0 so a developer is never blocked by the hook itself — only
 *    by a real, reported structural contradiction.
 *
 * `{{CORPUS}}` and `{{RAC_BIN}}` are substituted at generation time.
 */
const HOOK_SCRIPT_TEMPLATE = `#!/usr/bin/env python3
"""RAC Claude Code pre-edit hook (generated by the RAC extension, ADR-067).

Pipes proposed Edit/Write content to \`rac validate - --corpus\` and blocks the
edit (exit 2) only on a structural finding. Fails open on any internal error:
the hook never blocks a developer because of its own failure. Do not edit by
hand — re-run "RAC: Enable Claude Code pre-edit hook" to regenerate.
"""

import json
import os
import subprocess
import sys

# Substituted at generation time by the RAC extension.
CORPUS = {{CORPUS}}
RAC_BIN = {{RAC_BIN}}


def allow():
    # Exit 0 = allow the edit. Used for non-corpus files and every internal
    # error (fail-open, ADR-067: a hook fault must never block a developer).
    sys.exit(0)


def block(reason):
    # Exit 2 = block the edit; stderr is fed back to Claude as the reason.
    sys.stderr.write(reason)
    sys.exit(2)


def main():
    try:
        event = json.load(sys.stdin)
    except Exception:
        allow()

    tool = event.get("tool_name", "")
    tool_input = event.get("tool_input") or {}

    # Edit/Write carry a top-level file_path; MultiEdit nests file_path in each
    # edit. Take the top-level one, else the first edit's, so all three are
    # handled without assuming one shape.
    edits = tool_input.get("edits") or []
    file_path = tool_input.get("file_path") or ""
    if not file_path and edits:
        file_path = edits[0].get("file_path") or ""
    if not file_path or not file_path.endswith(".md"):
        allow()

    # Scope to Markdown files under the corpus directory only. Compare absolute,
    # normalised paths so a relative file_path resolves against the project dir.
    project_dir = event.get("cwd") or os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    corpus_abs = os.path.realpath(os.path.join(project_dir, CORPUS))
    target_abs = os.path.realpath(
        file_path if os.path.isabs(file_path) else os.path.join(project_dir, file_path)
    )
    try:
        if os.path.commonpath([corpus_abs, target_abs]) != corpus_abs:
            allow()
    except ValueError:
        allow()  # different drives / unrelated paths — not a corpus edit

    def field(d, *names):
        # Tolerate field-name variance across Claude Code versions
        # (content/file_text, old_str/old_string, ...).
        for name in names:
            if d.get(name) is not None:
                return d.get(name)
        return None

    # Reconstruct the *proposed* full document content.
    if tool == "Write":
        content = field(tool_input, "content", "file_text")
        if content is None:
            allow()
    else:
        # Edit / MultiEdit carry only the diff. Apply it to the on-disk file in
        # memory; if the file or an edit cannot be applied cleanly, fail open
        # (the post-edit guard still catches it after the write).
        try:
            with open(target_abs, "r", encoding="utf-8") as fh:
                content = fh.read()
        except Exception:
            allow()
        if not edits:
            old = field(tool_input, "old_string", "old_str")
            new = field(tool_input, "new_string", "new_str") or ""
            edits = [{"old_string": old, "new_string": new}] if old is not None else []
        for edit in edits:
            # MultiEdit may span files; only apply edits to the target document.
            edit_path = edit.get("file_path")
            if edit_path:
                edit_abs = os.path.realpath(
                    edit_path if os.path.isabs(edit_path)
                    else os.path.join(project_dir, edit_path)
                )
                if edit_abs != target_abs:
                    continue
            old = field(edit, "old_string", "old_str")
            new = field(edit, "new_string", "new_str") or ""
            if old is None or old not in content:
                allow()
            content = content.replace(old, new, 1)

    # The single deterministic gate: structural + corpus reference validation.
    try:
        result = subprocess.run(
            [RAC_BIN, "validate", "-", "--corpus", corpus_abs],
            input=content,
            capture_output=True,
            text=True,
            cwd=project_dir,
        )
    except Exception:
        allow()

    if result.returncode == 0:
        allow()

    # rac exited non-zero: a structural finding. Block with its report so the
    # developer sees exactly which decision the edit contradicts.
    report = (result.stdout or "").strip() or (result.stderr or "").strip()
    block(
        "RAC pre-edit guard blocked this edit — it introduces a structural "
        "contradiction with a recorded decision:\\n\\n" + report + "\\n"
    )


if __name__ == "__main__":
    main()
`;

/** A JSON string literal usable inside the generated Python (handles quoting). */
function pyString(value: string): string {
  return JSON.stringify(value);
}

/**
 * Render the hook script for a workspace.
 *
 * @param corpusRel the corpus directory relative to the workspace root (e.g. "rac")
 * @param racBin    the `rac` binary the extension runs (from `rac.path` or "rac")
 */
export function renderHookScript(corpusRel: string, racBin: string): string {
  return HOOK_SCRIPT_TEMPLATE.replace("{{CORPUS}}", pyString(corpusRel)).replace(
    "{{RAC_BIN}}",
    pyString(racBin),
  );
}

/** One registered PreToolUse hook entry in `.claude/settings.json`. */
interface PreToolUseEntry {
  matcher?: string;
  hooks?: Array<{ type?: string; command?: string }>;
}

interface ClaudeSettings {
  hooks?: { PreToolUse?: PreToolUseEntry[]; [k: string]: unknown };
  [k: string]: unknown;
}

/**
 * Merge the RAC pre-edit hook registration into existing Claude settings,
 * without clobbering anything else.
 *
 * Idempotent: a prior RAC registration (matched by the script marker in its
 * command) is replaced rather than duplicated, so re-running the enable command
 * is safe. The returned object is a new value; the caller serialises and writes
 * it. `command` is the shell command Claude Code runs for the matched tools.
 */
export function mergeHookSettings(existing: ClaudeSettings, command: string): ClaudeSettings {
  const settings: ClaudeSettings = { ...existing };
  const hooks = { ...(settings.hooks ?? {}) };
  const preToolUse: PreToolUseEntry[] = Array.isArray(hooks.PreToolUse)
    ? [...hooks.PreToolUse]
    : [];

  const entry: PreToolUseEntry = {
    matcher: HOOK_MATCHER,
    hooks: [{ type: "command", command }],
  };

  // Drop any prior RAC registration (idempotent re-run) — identified by the
  // generated script marker anywhere in a command — and any now-empty entry.
  const kept = preToolUse
    .map((e) => ({
      ...e,
      hooks: (e.hooks ?? []).filter((h) => !(h.command ?? "").includes(HOOK_COMMAND_MARKER)),
    }))
    .filter((e) => (e.hooks ?? []).length > 0);

  hooks.PreToolUse = [...kept, entry];
  settings.hooks = hooks;
  return settings;
}

/**
 * Remove the RAC pre-edit hook registration from Claude settings, leaving every
 * other hook intact (the idempotent "disable" half).
 */
export function removeHookSettings(existing: ClaudeSettings): ClaudeSettings {
  const settings: ClaudeSettings = { ...existing };
  if (!settings.hooks || !Array.isArray(settings.hooks.PreToolUse)) return settings;
  const hooks = { ...settings.hooks };
  hooks.PreToolUse = (hooks.PreToolUse as PreToolUseEntry[])
    .map((e) => ({
      ...e,
      hooks: (e.hooks ?? []).filter((h) => !(h.command ?? "").includes(HOOK_COMMAND_MARKER)),
    }))
    .filter((e) => (e.hooks ?? []).length > 0);
  settings.hooks = hooks;
  return settings;
}
